name: Rain CI
on: [push]

jobs:
  install-build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install deps
        run: nix develop -c pnpm install --frozen-lockfile

      - name: Build ./packages/sushi
        run: nix develop -c pnpm exec turbo run build --filter=./packages/sushi

      - name: Lint
        run: nix develop -c pnpm lint

      - name: Check ./packages/sushi Types
        run: nix develop -c pnpm exec turbo run check --filter=./packages/sushi

      - name: Test ./packages/sushi
        run: nix develop -c pnpm exec turbo run test --filter=./packages/sushi